---
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Install Dependencies
      run: |
        gem install test-unit
        make clean
    - name: Build and run Tests
      run: |
        make all
        make test
