---
name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
    - name: Install Dependencies
      run: |
        gem install test-unit
        make clean
    - name: Build and run Tests
      run: |
        make all
        make test
